//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listagem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        public int Id { get; set; }
        public Nullable<int> SelecaoCasaId { get; set; }
        public Nullable<int> PlacarCasa { get; set; }
        public Nullable<int> SelecaoVisitanteId { get; set; }
        public Nullable<int> PlacarVisitante { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> RodadaId { get; set; }
    
        public virtual Comentario Comentario { get; set; }
        public virtual Rodadas Rodadas { get; set; }
    }
}
