//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListagemDeNotificacoes2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selecoes
    {
        public Selecoes()
        {
            this.Jogadores = new HashSet<Jogadores>();
            this.Notificacoes = new HashSet<Notificacoes>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Jogadores> Jogadores { get; set; }
        public virtual ICollection<Notificacoes> Notificacoes { get; set; }
    }
}
