//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListagemDeNotificacoes2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Comentario = new HashSet<Comentario>();
            this.NotificacoesUsuarios = new HashSet<NotificacoesUsuarios>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public System.DateTime Nascimento { get; set; }
        public byte[] Foto { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> TimeFavoritoId { get; set; }
        public string perfil { get; set; }
    
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual ICollection<NotificacoesUsuarios> NotificacoesUsuarios { get; set; }
    }
}
