//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginCadastro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public int Id { get; set; }
        public string Apelido { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public byte[] Foto { get; set; }
        public string TimeFavorito { get; set; }
        public string CorFavorita { get; set; }
        public Nullable<System.DateTime> DatNascimento { get; set; }
    }
}
