//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparadorImagemDb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pikomon
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public byte[] Foto { get; set; }
        public string tipo { get; set; }
        public string Vantagem { get; set; }
        public string Fraqueza { get; set; }
    }
}
